server:
  port: 8089
  error:
    include-stacktrace: never
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookmingle
    username: #your db username
    password: #your password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
